org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Google AdMob banner config
ENABLE_MOBILE_ADS=true
ADMOB_APP_ID=ca-app-pub-6158185990205930~3503834531
ADMOB_BANNER_AD_UNIT_ID=ca-app-pub-6158185990205930/9974813464
APPLOVIN_SDK_KEY=
APPLOVIN_BANNER_AD_UNIT_ID=
