# Generated by Django 4.2.4 on 2024-12-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skistation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skistation',
            name='altitude',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
