# Generated by Django 4.2.4 on 2024-12-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skistation_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='skistation',
            name='distanceFromGrenoble',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
