# Generated by ChatGPT on 2026-02-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('certifications', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('max_group_size', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.instructorprofile')),
                ('ski_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_services', to='api.skistation')),
            ],
        ),
        migrations.AddField(
            model_name='skimateriallisting',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skimateriallisting',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skimateriallisting',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='skimateriallisting',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skimateriallisting',
            name='listing_type',
            field=models.CharField(choices=[('lend', 'Lend'), ('sell', 'Sell')], default='lend', max_length=10),
        ),
        migrations.AlterField(
            model_name='skimateriallisting',
            name='material_type',
            field=models.CharField(max_length=50),
        ),
    ]
