# Generated by Django 4.2.4 on 2026-02-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_expand_seed_related_varchar_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestore',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='servicestore',
            name='source_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
