# Generated by Django 4.2.4 on 2026-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_partner_reports_and_verified_deals'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='instructorreview',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructorreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instructorservice',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='instructorservice',
            name='ski_station',
        ),
        migrations.AlterModelOptions(
            name='crowdstatusupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pisteconditionreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='snowconditionupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='busline',
            name='departure_latitude',
        ),
        migrations.RemoveField(
            model_name='busline',
            name='departure_longitude',
        ),
        migrations.RemoveField(
            model_name='busline',
            name='route_points',
        ),
        migrations.RemoveField(
            model_name='servicestore',
            name='address',
        ),
        migrations.RemoveField(
            model_name='servicestore',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='servicestore',
            name='source_note',
        ),
        migrations.RemoveField(
            model_name='servicestore',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='skimateriallisting',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='skimateriallisting',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='skimateriallisting',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='skimateriallisting',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='skimateriallisting',
            name='listing_type',
        ),
        migrations.AlterField(
            model_name='busline',
            name='bus_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='busline',
            name='frequency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='busline',
            name='travel_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstatusupdate',
            name='crowd_level',
            field=models.CharField(choices=[('quiet', 'Peu de gens'), ('normal', 'Agreable'), ('busy', 'Bonde')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='pisteconditionreport',
            name='crowd_level',
            field=models.CharField(choices=[('quiet', 'Peu de gens'), ('normal', 'Agreable'), ('busy', 'Bonde')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicestore',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
        migrations.DeleteModel(
            name='InstructorReview',
        ),
        migrations.DeleteModel(
            name='InstructorService',
        ),
    ]
