# Generated by Django 4.2.4 on 2026-03-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0034_skistation_piste_map_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_type', models.CharField(choices=[('marketplace_seller', 'Marketplace Seller'), ('trusted_seller', 'Trusted Seller'), ('power_seller', 'Power Seller'), ('story_teller', 'Story Teller'), ('social_butterfly', 'Social Butterfly'), ('ski_expert', 'Ski Expert'), ('condition_watcher', 'Condition Watcher'), ('partner_matcher', 'Partner Matcher'), ('instructor_master', 'Instructor Master'), ('reviewer', 'Reviewer'), ('helpful_reviewer', 'Helpful Reviewer'), ('first_time', 'First Timer'), ('streak_king', 'Streak King'), ('collector', 'Collector')], max_length=30, unique=True)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(default='🏆', help_text='Emoji icon for the badge', max_length=10)),
                ('points_value', models.PositiveIntegerField(default=50, help_text='Points awarded when badge is earned')),
                ('requirement_description', models.TextField(help_text='Human readable requirements to earn this badge')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rarity', '-points_value'],
            },
        ),
        migrations.AlterModelOptions(
            name='busline',
            options={'ordering': ['bus_number']},
        ),
        migrations.AlterField(
            model_name='busline',
            name='ski_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_lines', to='api.skistation'),
        ),
        migrations.AlterField(
            model_name='skimateriallisting',
            name='material_type',
            field=models.CharField(choices=[('ski', 'Ski'), ('boots', 'Boots'), ('helmet', 'Helmet'), ('jacket', 'Jacket'), ('pants', 'Pants'), ('gloves', 'Gloves'), ('goggles', 'Goggles'), ('service', 'Service'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('other', 'Other')], default='ski', max_length=20),
        ),
        migrations.AlterField(
            model_name='skimateriallisting',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lend', 'For Loan'), ('service', 'Service')], default='sale', max_length=10),
        ),
        migrations.CreateModel(
            name='UserGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('badges_count', models.PositiveIntegerField(default=0)),
                ('daily_login_streak', models.PositiveIntegerField(default=0)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('total_listings_created', models.PositiveIntegerField(default=0)),
                ('total_deals_completed', models.PositiveIntegerField(default=0)),
                ('total_reviews_written', models.PositiveIntegerField(default=0)),
                ('average_seller_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Game Stats',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.gamificationbadge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='GamificationPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('listing_created', 'Created Marketplace Listing'), ('deal_completed', 'Completed Marketplace Deal'), ('listing_sold', 'Sold Item'), ('review_written', 'Wrote a Review'), ('review_received', 'Received Positive Review'), ('story_created', 'Posted Ski Story'), ('partner_post_created', 'Posted Ski Partner Request'), ('condition_report', 'Submitted Condition Report'), ('friend_added', 'Added Friend'), ('instructor_service', 'Completed Instructor Service'), ('first_login', 'First Login'), ('profile_completed', 'Completed Profile'), ('badge_earned', 'Achievement Earned'), ('daily_login', 'Daily Login Streak'), ('other', 'Other Activity')], max_length=30)),
                ('points_earned', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity')),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object (listing, deal, etc)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_gamific_user_id_3de58b_idx'), models.Index(fields=['activity_type'], name='api_gamific_activit_9c585e_idx')],
            },
        ),
    ]
