# Generated by Django 4.2.4 on 2026-03-27 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0035_gamificationbadge_alter_busline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skipartnerpost',
            name='departure_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='skipartnerpost',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skipartnerpost',
            name='is_carpool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skipartnerpost',
            name='total_seats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skipartnerpost',
            name='vehicle_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='CarpoolReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_reserved', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.skipartnerpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='carpoolreservation',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='uniq_carpool_reservation_per_post_user'),
        ),
    ]
