# Generated by Django 4.2.4 on 2026-03-27 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0036_skipartnerpost_departure_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(db_index=True, max_length=80)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('mobile', 'Mobile'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=10)),
                ('is_api', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature_name', '-created_at'], name='api_appusag_feature_725914_idx'), models.Index(fields=['platform', '-created_at'], name='api_appusag_platfor_0e810a_idx')],
            },
        ),
    ]
