# Generated by Django 4.2.4 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_appusageevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoolreservation',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('active', 'Active'),
                    ('rejected', 'Rejected'),
                    ('cancelled', 'Cancelled'),
                ],
                default='pending',
                max_length=12,
            ),
        ),
    ]
