# Generated by Django 4.2.15 on 2026-08-30 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0043_friendinvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busline',
            name='live_status',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='busline',
            name='live_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busline',
            name='next_departure_at',
            field=models.DateTimeField(blank=True, help_text='Next verified departure, supplied by the operator feed', null=True),
        ),
        migrations.AddField(
            model_name='skistationcamera',
            name='last_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skistationcamera',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_budget_eur',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_stations',
            field=models.ManyToManyField(blank=True, related_name='favoured_by_profiles', to='api.skistation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seeking_carpool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skiing_level',
            field=models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance')], default='intermediate', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transport_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='StationOfficialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('source_type', models.CharField(choices=[('rss', 'RSS/Atom'), ('page', 'Official page')], default='rss', max_length=8)),
                ('language', models.CharField(choices=[('fr', 'Francais'), ('en', 'English')], default='fr', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('ski_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_sources', to='api.skistation')),
            ],
        ),
        migrations.CreateModel(
            name='StationLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifts_open', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lifts_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pistes_open', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pistes_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('snow_depth_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('snow_fall_24h_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weather_summary', models.CharField(blank=True, max_length=120)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ski_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_status', to='api.skistation')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('story', 'Story'), ('listing', 'Marketplace listing'), ('partner', 'Partner post'), ('message', 'Message')], max_length=12)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned')], default='open', max_length=12)),
                ('moderator_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stationofficialsource',
            constraint=models.UniqueConstraint(fields=('ski_station', 'url'), name='uniq_station_official_source'),
        ),
        migrations.AddConstraint(
            model_name='moderationreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'target_type', 'target_id'), name='uniq_report_per_target_user'),
        ),
    ]
