# Generated by Django 4.2.4 on 2026-09-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_busline_live_status_busline_live_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrenoblePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description_fr', models.TextField()),
                ('description_en', models.TextField()),
                ('walk_fr', models.TextField()),
                ('walk_en', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('photo_credit', models.CharField(blank=True, max_length=500)),
                ('photo_source_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='skistation',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='skistation',
            name='photo_source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
