# Generated by Django 4.2.4 on 2026-09-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_grenobleplace_skistation_photo_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skistationcamera',
            name='camera_type',
            field=models.CharField(choices=[('live_stream', 'Live Stream (MJPEG)'), ('hls_stream', 'HLS Stream (m3u8)'), ('snapshot', 'Snapshot Only'), ('embedded', 'Embedded provider viewer')], default='snapshot', max_length=20),
        ),
    ]
