# Generated by Django 4.2.4 on 2026-09-08 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_skistationcamera_camera_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureFeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('topic', models.CharField(choices=[('museum', 'Museums'), ('performing_arts', 'Performing arts'), ('science', 'Science and families')], max_length=30)),
                ('language', models.CharField(default='fr', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='skinewsitem',
            name='category',
            field=models.CharField(choices=[('ski', 'Ski'), ('culture', 'Culture')], db_index=True, default='ski', max_length=12),
        ),
        migrations.AddField(
            model_name='skinewsitem',
            name='culture_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='api.culturefeedsource'),
        ),
    ]
