# Generated by Django 4.2.4 on 2026-09-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_seed_grenoble_culture_feeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinewsitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='skinewsitem',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='skinewsitem',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
