# Generated by Django 4.2.15 on 2026-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_skipartnerpost_carpool_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_type', models.CharField(max_length=12)),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=180)),
                ('accommodation_type', models.CharField(blank=True, max_length=40)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('website_url', models.URLField(blank=True, max_length=700)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='accommodationplace',
            constraint=models.UniqueConstraint(fields=('osm_type', 'osm_id'), name='unique_osm_accommodation'),
        ),
    ]
