# Generated by Django 4.2.4 on 2024-12-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skistation',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
